export const CREATE_EVENT_REQUEST = 'CREATE_EVENT_REQUEST';
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';
export const CREATE_EVENT_FAIL = 'CREATE_EVENT_FAIL';

export const GET_USER_EVENT = 'GET_USER_EVENT';

export const GET_SINGLE_EVENT = 'GET_SINGLE_EVENT';
